# Generated by Django 5.1.2 on 2024-11-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Danh sách sản phẩm'},
        ),
    ]
