# Generated by Django 5.1.2 on 2024-11-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
